import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:frigo_zen/models/activity_log.dart';
import 'package:frigo_zen/services/household_service.dart';

class HistoryService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final HouseholdService _householdService = HouseholdService();

  Future<void> logActivity({
    required ActivityType type,
    required String itemName,
    Map<String, dynamic>? details,
  }) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      final householdId = await _householdService.getUserHouseholdId();
      if (householdId == null) return;

      // Create activity log object
      final activity = ActivityLog(
        id: '', // Generated by Firestore
        type: type,
        itemName: itemName,
        userId: user.uid,
        timestamp: DateTime.now(),
        details: details,
      );

      // Add to Firestore sub-collection
      await _firestore
          .collection('households')
          .doc(householdId)
          .collection('history')
          .add(activity.toMap());
          
    } catch (e) {
      // Fail silently to not disrupt user flow
      print('Error logging activity: $e');
    }
  }

  Stream<List<ActivityLog>> getHistoryStream() async* {
    final householdId = await _householdService.getUserHouseholdId();
    if (householdId == null) {
      yield [];
      return;
    }

    yield* _firestore
        .collection('households')
        .doc(householdId)
        .collection('history')
        .orderBy('timestamp', descending: true)
        .limit(50) // Limit to last 50 actions
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => ActivityLog.fromSnapshot(doc))
          .toList();
    });
  }


  Future<List<ActivityLog>> getSpendingHistory() async {
    final householdId = await _householdService.getUserHouseholdId();
    if (householdId == null) return [];

    final now = DateTime.now();
    final sixMonthsAgo = now.subtract(const Duration(days: 180));

    final snapshot = await _firestore
        .collection('households')
        .doc(householdId)
        .collection('history')
        .where('type', isEqualTo: ActivityType.bought.name)
        .where('timestamp', isGreaterThanOrEqualTo: Timestamp.fromDate(sixMonthsAgo))
        .orderBy('timestamp', descending: true)
        .get();

    return snapshot.docs.map((doc) => ActivityLog.fromSnapshot(doc)).toList();
  }

  // DEBUG ONLY
  Future<void> generateFakeData() async {
    final householdId = await _householdService.getUserHouseholdId();
    if (householdId == null) return;
    
    final random = DateTime.now().millisecondsSinceEpoch;
    final collection = _firestore.collection('households').doc(householdId).collection('history');

    // Generate 10 entries over last 3 months
    final now = DateTime.now();
    
    final items = [
      {'name': 'Pommes', 'price': 2.50},
      {'name': 'Lait', 'price': 1.20},
      {'name': 'Viande', 'price': 15.00},
      {'name': 'Pâtes', 'price': 0.90},
      {'name': 'Fromage', 'price': 4.50},
    ];

    for (int i = 0; i < 20; i++) {
        final item = items[i % items.length];
        final daysAgo = (i * 5) % 90; // Spread over 3 months
        final date = now.subtract(Duration(days: daysAgo));
        
        final activity = ActivityLog(
          id: '',
          type: ActivityType.bought,
          itemName: item['name'] as String,
          userId: _auth.currentUser?.uid ?? 'test',
          timestamp: date,
          details: {
             'price': item['price'],
             'quantity': 1,
             'action': 'fake_data'
          }
        );
        await collection.add(activity.toMap()..['timestamp'] = Timestamp.fromDate(date));
    }
  }
}
