import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:frigo_zen/models/activity_log.dart';
import 'package:frigo_zen/services/household_service.dart';

class HistoryService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final HouseholdService _householdService = HouseholdService();

  Future<void> logActivity({
    required ActivityType type,
    required String itemName,
    Map<String, dynamic>? details,
  }) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      final householdId = await _householdService.getUserHouseholdId();
      if (householdId == null) return;

      // Create activity log object
      final activity = ActivityLog(
        id: '', // Generated by Firestore
        type: type,
        itemName: itemName,
        userId: user.uid,
        userName: user.displayName ?? 'Utilisateur',
        userAvatar: user.photoURL ?? '',
        timestamp: DateTime.now(),
        details: details,
      );

      // Add to Firestore sub-collection
      await _firestore
          .collection('households')
          .doc(householdId)
          .collection('history')
          .add(activity.toMap());
          
    } catch (e) {
      // Fail silently to not disrupt user flow
      print('Error logging activity: $e');
    }
  }

  Stream<List<ActivityLog>> getHistoryStream() async* {
    final householdId = await _householdService.getUserHouseholdId();
    if (householdId == null) {
      yield [];
      return;
    }

    yield* _firestore
        .collection('households')
        .doc(householdId)
        .collection('history')
        .orderBy('timestamp', descending: true)
        .limit(50) // Limit to last 50 actions
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => ActivityLog.fromSnapshot(doc))
          .toList();
    });
  }
}
