// Mocks generated by Mockito 5.4.6 from annotations
// in frigo_zen/test/screens/planning/meal_planner_crash_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:firebase_auth/firebase_auth.dart' as _i15;
import 'package:frigo_zen/models/batch.dart' as _i10;
import 'package:frigo_zen/models/household.dart' as _i17;
import 'package:frigo_zen/models/inventory_item.dart' as _i8;
import 'package:frigo_zen/models/meal_plan.dart' as _i3;
import 'package:frigo_zen/models/shopping_item.dart' as _i11;
import 'package:frigo_zen/repositories/household_repository.dart' as _i16;
import 'package:frigo_zen/services/auth_service.dart' as _i14;
import 'package:frigo_zen/services/revenue_provider.dart' as _i12;
import 'package:frigo_zen/viewmodels/inventory_view_model.dart' as _i5;
import 'package:frigo_zen/viewmodels/meal_planner_view_model.dart' as _i2;
import 'package:frigo_zen/viewmodels/shopping_view_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:purchases_flutter/purchases_flutter.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MealPlannerViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealPlannerViewModel extends _i1.Mock
    implements _i2.MealPlannerViewModel {
  @override
  List<_i3.MealPlan> get meals =>
      (super.noSuchMethod(
            Invocation.getter(#meals),
            returnValue: <_i3.MealPlan>[],
            returnValueForMissingStub: <_i3.MealPlan>[],
          )
          as List<_i3.MealPlan>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void init(String? householdId) => super.noSuchMethod(
    Invocation.method(#init, [householdId]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> addMeal(
    DateTime? date,
    _i3.MealType? type,
    String? name, {
    List<String>? ingredients = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addMeal,
              [date, type, name],
              {#ingredients: ingredients},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMeal(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMeal, [mealId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateMeal(
    String? mealId,
    String? newName,
    List<String>? newIngredients,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMeal, [mealId, newName, newIngredients]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> generateShoppingList(
    _i5.InventoryViewModel? inventory,
    _i6.ShoppingViewModel? shopping,
    String? languageCode, {
    required DateTime? start,
    required DateTime? end,
    bool? isPro = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateShoppingList,
              [inventory, shopping, languageCode],
              {#start: start, #end: end, #isPro: isPro},
            ),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  void setMealsForTesting(List<_i3.MealPlan>? meals) => super.noSuchMethod(
    Invocation.method(#setMealsForTesting, [meals]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [InventoryViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryViewModel extends _i1.Mock
    implements _i5.InventoryViewModel {
  @override
  List<_i8.InventoryItem> get items =>
      (super.noSuchMethod(
            Invocation.getter(#items),
            returnValue: <_i8.InventoryItem>[],
            returnValueForMissingStub: <_i8.InventoryItem>[],
          )
          as List<_i8.InventoryItem>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.LocationFilter get selectedFilter =>
      (super.noSuchMethod(
            Invocation.getter(#selectedFilter),
            returnValue: _i5.LocationFilter.all,
            returnValueForMissingStub: _i5.LocationFilter.all,
          )
          as _i5.LocationFilter);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  List<_i8.InventoryItem> get filteredItems =>
      (super.noSuchMethod(
            Invocation.getter(#filteredItems),
            returnValue: <_i8.InventoryItem>[],
            returnValueForMissingStub: <_i8.InventoryItem>[],
          )
          as List<_i8.InventoryItem>);

  @override
  int get expiringSoonCount =>
      (super.noSuchMethod(
            Invocation.getter(#expiringSoonCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  Map<String, int> get nutriscoreDistribution =>
      (super.noSuchMethod(
            Invocation.getter(#nutriscoreDistribution),
            returnValue: <String, int>{},
            returnValueForMissingStub: <String, int>{},
          )
          as Map<String, int>);

  @override
  Map<String, int> get categoryDistribution =>
      (super.noSuchMethod(
            Invocation.getter(#categoryDistribution),
            returnValue: <String, int>{},
            returnValueForMissingStub: <String, int>{},
          )
          as Map<String, int>);

  @override
  Map<String, int> get locationDistribution =>
      (super.noSuchMethod(
            Invocation.getter(#locationDistribution),
            returnValue: <String, int>{},
            returnValueForMissingStub: <String, int>{},
          )
          as Map<String, int>);

  @override
  List<_i8.InventoryItem> get expiringItems =>
      (super.noSuchMethod(
            Invocation.getter(#expiringItems),
            returnValue: <_i8.InventoryItem>[],
            returnValueForMissingStub: <_i8.InventoryItem>[],
          )
          as List<_i8.InventoryItem>);

  @override
  Map<String, int> get storeDistribution =>
      (super.noSuchMethod(
            Invocation.getter(#storeDistribution),
            returnValue: <String, int>{},
            returnValueForMissingStub: <String, int>{},
          )
          as Map<String, int>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void init(String? householdId) => super.noSuchMethod(
    Invocation.method(#init, [householdId]),
    returnValueForMissingStub: null,
  );

  @override
  void setFilter(_i5.LocationFilter? filter) => super.noSuchMethod(
    Invocation.method(#setFilter, [filter]),
    returnValueForMissingStub: null,
  );

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#setSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> addItem(_i8.InventoryItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#addItem, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateItem(_i8.InventoryItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, [itemId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> incrementItemQuantity(_i8.InventoryItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#incrementItemQuantity, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> decrementItemQuantity(_i8.InventoryItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#decrementItemQuantity, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBatchDate(
    _i8.InventoryItem? item,
    _i10.Batch? batch,
    DateTime? newDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBatchDate, [item, batch, newDate]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateItemName(_i8.InventoryItem? item, String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemName, [item, newName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateItemCategory(
    _i8.InventoryItem? item,
    String? newCategory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemCategory, [item, newCategory]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBatchDetails(
    _i8.InventoryItem? item,
    _i10.Batch? oldBatch,
    _i10.Batch? newBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBatchDetails, [item, oldBatch, newBatch]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool doesItemExist(String? canonicalName) =>
      (super.noSuchMethod(
            Invocation.method(#doesItemExist, [canonicalName]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ShoppingViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingViewModel extends _i1.Mock implements _i6.ShoppingViewModel {
  @override
  List<_i11.ShoppingItem> get items =>
      (super.noSuchMethod(
            Invocation.getter(#items),
            returnValue: <_i11.ShoppingItem>[],
            returnValueForMissingStub: <_i11.ShoppingItem>[],
          )
          as List<_i11.ShoppingItem>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void init(String? householdId) => super.noSuchMethod(
    Invocation.method(#init, [householdId]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> addItem(_i11.ShoppingItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#addItem, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateItem(_i11.ShoppingItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, [itemId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearList() =>
      (super.noSuchMethod(
            Invocation.method(#clearList, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleItemChecked(_i11.ShoppingItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#toggleItemChecked, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i11.ShoppingItem?> resolveItemName(
    String? name,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resolveItemName, [name, languageCode]),
            returnValue: _i4.Future<_i11.ShoppingItem?>.value(),
            returnValueForMissingStub: _i4.Future<_i11.ShoppingItem?>.value(),
          )
          as _i4.Future<_i11.ShoppingItem?>);

  @override
  _i4.Future<void> addItemByName(String? name, String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#addItemByName, [name, languageCode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addItemsFromRecipe(
    List<String>? ingredientNames,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addItemsFromRecipe, [
              ingredientNames,
              languageCode,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleSelectAll() =>
      (super.noSuchMethod(
            Invocation.method(#toggleSelectAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> moveCheckedItemsToInventory() =>
      (super.noSuchMethod(
            Invocation.method(#moveCheckedItemsToInventory, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RevenueProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRevenueProvider extends _i1.Mock implements _i12.RevenueProvider {
  @override
  bool get isPro =>
      (super.noSuchMethod(
            Invocation.getter(#isPro),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void setCustomerInfo(_i13.CustomerInfo? info) => super.noSuchMethod(
    Invocation.method(#setCustomerInfo, [info]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> restorePurchases() =>
      (super.noSuchMethod(
            Invocation.method(#restorePurchases, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i14.AuthService {
  @override
  _i4.Stream<_i15.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i15.User?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i15.User?>.empty(),
          )
          as _i4.Stream<_i15.User?>);

  @override
  _i4.Future<_i15.UserCredential?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<_i15.UserCredential?>.value(),
            returnValueForMissingStub: _i4.Future<_i15.UserCredential?>.value(),
          )
          as _i4.Future<_i15.UserCredential?>);

  @override
  _i4.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [HouseholdRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHouseholdRepository extends _i1.Mock
    implements _i16.HouseholdRepository {
  @override
  _i4.Future<String?> getHouseholdIdForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getHouseholdIdForUser, [userId]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Stream<_i17.Household?> getHouseholdStream(String? householdId) =>
      (super.noSuchMethod(
            Invocation.method(#getHouseholdStream, [householdId]),
            returnValue: _i4.Stream<_i17.Household?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i17.Household?>.empty(),
          )
          as _i4.Stream<_i17.Household?>);
}
