import 'package:flutter/material.dart';
import 'package:frigo_zen/screens/core/navigation_shell.dart';
// Import Firebase packages
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // File generated by FlutterFire

// The main function must be "async" to await initialization
Future<void> main() async {
  // Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase with default options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const FrigoZenApp());
}

class FrigoZenApp extends StatelessWidget {
  const FrigoZenApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "FrigoZen",
      theme: ThemeData(
        primarySwatch: Colors.green,
        useMaterial3: true,
        navigationBarTheme: NavigationBarThemeData(
          indicatorColor: Colors.green[100],
          labelTextStyle: MaterialStateProperty.all(
            const TextStyle(fontSize: 14, fontWeight: FontWeight.w500),
          ),
        ),
      ),
      debugShowCheckedModeBanner: false,
      home: const NavigationShell(),
    );
  }
}
