import 'package:flutter/material.dart';
import 'package:frigo_zen/screens/core/auth_gate.dart';
// Import Firebase packages
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // File generated by FlutterFire

// 2. Créer un "Provider" simple pour notre inventaire
// Il tiendra juste la liste des noms d'articles de l'inventaire.
class InventoryProvider with ChangeNotifier {
  List<String> _itemNames = []; // Liste privée

  // "Getter" public pour que les autres widgets puissent lire la liste
  List<String> get itemNames => _itemNames;

  // Fonction pour mettre à jour la liste
  void updateInventory(List<String> newItemNames) {
    _itemNames = newItemNames;
    notifyListeners(); // Informe les widgets qui écoutent que les données ont changé
  }

  // Fonction pour vérifier si un article existe (insensible à la casse)
  bool doesItemExist(String name) {
    final lowerCaseName = name.toLowerCase().trim();
    return _itemNames.any((item) => item.toLowerCase().trim() == lowerCaseName);
  }
}

// The main function must be "async" to await initialization
Future<void> main() async {
  // Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase with default options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 3. Envelopper l'application dans le Provider
  runApp(
    ChangeNotifierProvider(
      create: (context) => InventoryProvider(), // On crée notre provider
      child: const FrigoZenApp(), // Notre application est l'enfant
    ),
  );
}

class FrigoZenApp extends StatelessWidget {
  const FrigoZenApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "FrigoZen",
      theme: ThemeData(
        primarySwatch: Colors.green,
        useMaterial3: true,
        navigationBarTheme: NavigationBarThemeData(
          indicatorColor: Colors.green[100],
          labelTextStyle: MaterialStateProperty.all(
            const TextStyle(fontSize: 14, fontWeight: FontWeight.w500),
          ),
        ),
      ),
      debugShowCheckedModeBanner: false,
      home: const AuthGate(),
    );
  }
}
