// Mocks generated by Mockito 5.4.6 from annotations
// in frigo_zen/test/viewmodels/inventory_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:frigo_zen/models/batch.dart' as _i5;
import 'package:frigo_zen/models/inventory_item.dart' as _i4;
import 'package:frigo_zen/repositories/inventory_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i2.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.InventoryItem>> getInventoryStream(
    String? householdId, {
    String? location,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getInventoryStream,
              [householdId],
              {#location: location},
            ),
            returnValue: _i3.Stream<List<_i4.InventoryItem>>.empty(),
          )
          as _i3.Stream<List<_i4.InventoryItem>>);

  @override
  _i3.Future<void> addInventoryItem(
    String? householdId,
    _i4.InventoryItem? item,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addInventoryItem, [householdId, item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateInventoryItem(
    String? householdId,
    _i4.InventoryItem? item,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateInventoryItem, [householdId, item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteInventoryItem(String? householdId, String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInventoryItem, [householdId, itemId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.InventoryItem?> findExistingItem(
    String? householdId,
    String? canonicalName,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findExistingItem, [
              householdId,
              canonicalName,
              name,
            ]),
            returnValue: _i3.Future<_i4.InventoryItem?>.value(),
          )
          as _i3.Future<_i4.InventoryItem?>);

  @override
  _i3.Future<void> upsertInventoryItem(
    String? householdId,
    _i4.InventoryItem? newItem,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertInventoryItem, [householdId, newItem]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  DateTime getEarliestDate(List<_i5.Batch>? batches) =>
      (super.noSuchMethod(
            Invocation.method(#getEarliestDate, [batches]),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#getEarliestDate, [batches]),
            ),
          )
          as DateTime);
}
